@hostname = http://localhost
@port = 3000
@url = {{hostname}}:{{port}}


//Recuperar opiniones por ID
###
GET {{url}}/api/comentarios/


// Recuperar opiniones por ID de cada actividad
###
GET {{url}}/api/comentarios/actividades/6